# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: ASQF Automation pipeline

on:
  workflow_dispatch:
    inputs:
      endpointurl:
        description: 'endpoint url'
        default: http://localhost:8080/
        required: true
        type: string

jobs:    
  build:

    runs-on: ubuntu-latest
    env:
      endpoint: http://localhost:8080/

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn clean install
